---
- name: Playbook entrainement installation
  hosts: client
  remote_user: ansible
  become: yes
  vars:
    user: toto

  tasks:
    - name: 1. Copy du repo Oracle
      become: yes
      copy:
        src: /etc/ansible/files/oracle.repo
        dest: /etc/yum.repos.d/oracle.repo

    - name: 2. Copy de la clef GPG du  repo Oracle
      become: yes
      copy:
        src: /etc/ansible/files/RPM-GPG-KEY-oracle-ol7
        dest: /etc/yum.repos.d/RPM-GPG-KEY-oracle-ol7

    - name: 3. Installer apache2
      become: yes
      yum:
        name: httpd
        state: present
        update_cache: yes

    - name: 4. Installer php
      become: yes
      yum:
        name: php
        state: present


    - name: 5. Installer extension php
      become: yes
      yum: name={{ item }} state=present
      with_items:
        - php-pdo
        - php-mysql
        - php-soap
        - php-pear
        - php-common
        - php-cli

    - name: 6. Installation de MariaDB
      become: yes
      yum:
        name: mariadb-server
        state: present

    - name: 7. Demarrer le service httpd
      become: yes
      service:
        name: httpd
        state: started
        enabled: yes

    - name: 8. Demarrer le service MariaDB
      become: yes
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: 9. Changer de fichier index
      become: yes
      copy:
        src: /etc/ansible/files/index-ansible.php
        dest: /var/www/html/index.php
        owner: root
        group: root
        mode: 0644
      notify: restart httpd

    - name: 10. Creation de l'utilisateur {{ user }}
      become: yes
      user:
        name: "{{ user }}"
        shell: /bin/sh
        createhome: yes
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: 11. Utilisation de template sudoers
      become: yes
      template:
        src: /etc/ansible/templates/sudoers.j2
        dest: /etc/sudoers.d/{{ user }}
        validate: '/usr/sbin/visudo -cf %s'

    - name: 12. Creer 4 fichiers
      become: yes
      file:
        dest: "/home/ansible/file_{{ item }}"
        state: touch
        owner: ansible
        group: ansible
        mode: 0644
      with_sequence: start=1 end=4 stride=1

    - name: 13. Installation de Samba
      become: yes
      yum:
       name: samba
       state: present
      when: ansible_os_family == "RedHat"

    - name: 14. Demarrer samba
      become: yes
      service:
        name: smb
        state: started
        enabled: yes

    - name: 15. Creation d'un dossier
      become: yes
      file:
        path: /srv/samba/commun
        state: directory
        mode: 1777

    - name: 16. Modification du fichier samba.conf
      become: yes
      lineinfile:
        dest: /etc/samba/smb.conf
        line: 'include /etc/samba/smb.conf.ansible'
        backup: yes

    - name: 17. Copy du fichier smb.conf.ansible
      become: yes
      copy:
        src: /etc/ansible/files/samba.redhat.ansible.conf
        dest: /etc/samba/smb.conf.ansible
        owner: root
        group: root
      notify:
        - restart samba

    - name: 18. Create firewall rule
      become: yes
      command: "/usr/bin/firewall-cmd --permanent --add-service=samba"

    - name: 19. Reload firewall
      become: yes
      command: "/usr/bin/firewall-cmd --reload"


  handlers:
    - name: restart httpd
      service:
        name: http
        state: restarted

    - name: restart samba
      service:
        name: smb
        state: restarted

...
